## Задание 1. Обучите модель градиентного бустинга

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive, files
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
df = pd.read_csv(file_path)
df

Unnamed: 0  Answer  inn_act  novelty  inn_prod  size  climate   age  \
0              0       1      0.0     0.00      0.00   4.0      7.0  35.0   
1              1       1      0.0     0.00      0.00   6.0      8.0  64.0   
2              2       1      1.0     0.24      0.78   3.0      8.0  26.0   
3              3       0      0.0     0.00      0.00   5.0      2.0  55.0   
4              4       1      1.0     0.18      0.91   5.0      5.0  43.0   
...          ...     ...      ...      ...       ...   ...      ...   ...   
1371        1371       0      0.0     0.00      0.00   3.0      1.0  31.0   
1372        1372       0      1.0     0.13      0.57   8.0      5.0  48.0   
1373        1373       0      1.0     0.05      0.16   5.0      6.0  29.0   
1374        1374       0      0.0     0.00      0.00   7.0     10.0  65.0   
1375        1375       1      0.0     0.00      0.00   2.0      7.0  41.0   

      competition  technologe_acq  ...  main_ag  Int_property  \
0               3               1  ...      1.0             0   
1               1               0  ...      1.0             1   
2               2               0  ...      1.0             0   
3               3               0  ...      1.0             0   
4               3               1  ...      3.0             1   
...           ...             ...  ...      ...           ...   
1371            1               0  ...      1.0             1   
1372            1               0  ...      1.0             0   
1373            5               0  ...      1.0             0   
1374            5               0  ...      1.0             1   
1375            3               1  ...      1.0             1   

      boss_experience  papers  wifi  MBA  passport  mortgage  green  Type  
0                   0       0     0    0      18.8       7.1      1     2  
1                   0      79     0    0      19.6      15.7      2     2  
2                   1     110     0    0      26.4       9.6      1     1  
3                   0       0     0    0      52.6      18.1      1     4  
4                   1       0     0    0       8.3      13.4      3     1  
...               ...     ...   ...  ...       ...       ...    ...   ...  
1371                0       0     0    0      53.7       7.4      1     4  
1372                1       0     0    0      41.8      15.9      1     3  
1373                1       0     0    0      36.0      17.0      1     3  
1374                0       0     0    0      81.1       6.7      1     4  
1375                0       0     0    1      22.3      14.2      1     2  

[1376 rows x 25 columns]

In [ ]:
!pip install python-docx
import docx

desc = docx.Document(doc_path)
print(*[par.text for par in desc.paragraphs], sep = '\n')

Описание переменных
Answer - компания инновационно-активная в 2018 году (0 -нет, 1 -да)

age - возраст руководителя в 2017 году
boss_experience – наличие успешного опыта у руководителя предприятия по 
реализации инновационных проектов по оценке сотрудников (0-нет, 1 -да)
climate - оценка предприятием условий для создания и распространения инноваций на рынке (10- максимально благоприятные, 0 - крайне неблагоприятные)    
competition- оценка компанией степени конкуренции на рынке (1- минимум, 5- максимум)
green – озелененность территории (до 5 баллов, 5 баллов -максимум)
inn_act - компания инновационно-активная в 2017 году (0-нет, 1-да)
inn_prod - доля продаж инновационной продукции в общем объеме продаж компании
Int_property – оценка предприятием степени надежности защиты интеллектуальной 
собственности (0-недостаточная защита, 1- надежная защита)
main_ag - расположение головной организации (1- Россия, 2- в странах СНГ, 3- в странах ЕС, 4- США, Канада, 5- другое)
market – наиболее важны

In [ ]:
df = df.drop(columns=['Type', 'Unnamed: 0'])

In [ ]:
df.describe().T

count       mean        std   min    25%    50%     75%  \
Answer              1376.0   0.444041   0.497039   0.0   0.00   0.00   1.000   
inn_act             1376.0   0.481831   0.499851   0.0   0.00   0.00   1.000   
novelty             1376.0   0.096628   0.154323   0.0   0.00   0.00   0.130   
inn_prod            1376.0   0.237834   0.304236   0.0   0.00   0.00   0.480   
size                1376.0   4.694767   2.526917   1.0   2.00   5.00   7.000   
climate             1376.0   5.073401   3.138220   0.0   2.00   5.00   8.000   
age                 1376.0  49.212936  14.090683  23.0  38.00  51.00  61.000   
competition         1376.0   2.907703   1.240902   1.0   2.00   3.00   4.000   
technologe_acq      1376.0   0.248547   0.432327   0.0   0.00   0.00   0.000   
RD                  1376.0   0.265182   0.206641   0.0   0.07   0.25   0.430   
market              1376.0   1.582849   0.802974   1.0   1.00   1.00   2.000   
novelty_tech        1376.0  13.366541  20.161046   0.0   0.00   0.00  23.960   
marketing_inn       1376.0   0.459302   0.498522   0.0   0.00   0.00   1.000   
organizational_inn  1376.0   0.383721   0.486468   0.0   0.00   0.00   1.000   
main_ag             1376.0   1.180233   0.647963   1.0   1.00   1.00   1.000   
Int_property        1376.0   0.438227   0.496350   0.0   0.00   0.00   1.000   
boss_experience     1376.0   0.481831   0.499851   0.0   0.00   0.00   1.000   
papers              1376.0  34.103198  42.736447   0.0   0.00   1.00  69.000   
wifi                1376.0   0.236192   0.424896   0.0   0.00   0.00   0.000   
MBA                 1376.0   0.061773   0.240831   0.0   0.00   0.00   0.000   
passport            1376.0  37.581468  19.042908   4.2  22.90  36.50  50.750   
mortgage            1376.0   9.246076   5.432982   0.0   4.40   9.10  13.925   
green               1376.0   1.521802   0.663515   1.0   1.00   1.00   2.000   

                       max  
Answer                1.00  
inn_act               1.00  
novelty               0.79  
inn_prod              0.93  
size                  9.00  
climate              10.00  
age                  72.00  
competition           5.00  
technologe_acq        1.00  
RD                    0.67  
market                5.00  
novelty_tech         78.68  
marketing_inn         1.00  
organizational_inn    1.00  
main_ag               5.00  
Int_property          1.00  
boss_experience       1.00  
papers              133.00  
wifi                  1.00  
MBA                   1.00  
passport             87.20  
mortgage             18.90  
green                 5.00

In [ ]:
df['Answer'].value_counts()

0    765
1    611
Name: Answer, dtype: int64

Классы сбалансированы, корректировать данные не нужно

In [ ]:
X = df.drop(columns='Answer')
y = df.Answer

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 888)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

clf = GradientBoostingClassifier().fit(X_train, y_train)
clf

GradientBoostingClassifier()

In [ ]:
clf.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

**Описание основных параметров модели**  
Максимальная глубина деревьев решений в модели - 3  
Количество базовых моделей (деревьев) в ансамбле - 100  
Функция потерь - log-loss

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

y_pred = clf.predict(X_test)

y_true = y_test

accuracy = accuracy_score(y_true, y_pred)
print(f'Accuracy: {accuracy:.4f}')

precision = precision_score(y_true, y_pred)
print(f'Precision: {precision:.4f}')

recall = recall_score(y_true, y_pred)
print(f'Recall: {recall:.4f}')

f1 = f1_score(y_true, y_pred)
print(f'F1 Score: {f1:.4f}')

conf_matrix = confusion_matrix(y_true, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_true, y_pred)
print('Classification Report:')
print(class_report)

Accuracy: 0.9187
Precision: 0.9196
Recall: 0.8971
F1 Score: 0.9082
Confusion Matrix:
[[235  16]
 [ 21 183]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       251
           1       0.92      0.90      0.91       204

    accuracy                           0.92       455
   macro avg       0.92      0.92      0.92       455
weighted avg       0.92      0.92      0.92       455



In [ ]:
pd.Series(index = clf.feature_names_in_, data = clf.feature_importances_).sort_values(ascending = False)

passport              0.717393
novelty               0.083770
RD                    0.045386
climate               0.043186
technologe_acq        0.036829
competition           0.031696
main_ag               0.018072
market                0.008261
novelty_tech          0.003205
age                   0.002508
inn_prod              0.002452
marketing_inn         0.001702
mortgage              0.001455
size                  0.001310
MBA                   0.000760
boss_experience       0.000490
papers                0.000457
green                 0.000402
Int_property          0.000365
inn_act               0.000206
wifi                  0.000093
organizational_inn    0.000000
dtype: float64

## Задание 2. Обучите модель случайного леса и сравните результаты с градиентным бустингом

In [ ]:
from sklearn import ensemble


randomforest = ensemble.RandomForestClassifier()
randomforest.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = randomforest.predict(X_test)
y_true = y_test

accuracy = accuracy_score(y_true, y_pred)
print(f'Accuracy: {accuracy:.4f}')

precision = precision_score(y_true, y_pred)
print(f'Precision: {precision:.4f}')

recall = recall_score(y_true, y_pred)
print(f'Recall: {recall:.4f}')

f1 = f1_score(y_true, y_pred)
print(f'F1 Score: {f1:.4f}')

conf_matrix = confusion_matrix(y_true, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_true, y_pred)
print('Classification Report:')
print(class_report)

Accuracy: 0.9187
Precision: 0.9239
Recall: 0.8922
F1 Score: 0.9077
Confusion Matrix:
[[236  15]
 [ 22 182]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.94      0.93       251
           1       0.92      0.89      0.91       204

    accuracy                           0.92       455
   macro avg       0.92      0.92      0.92       455
weighted avg       0.92      0.92      0.92       455



In [ ]:
pd.Series(index=randomforest.feature_names_in_, data=randomforest.feature_importances_).sort_values(ascending = False)

passport              0.400949
climate               0.091169
novelty               0.083088
RD                    0.074027
technologe_acq        0.064218
competition           0.041993
novelty_tech          0.026931
marketing_inn         0.024604
main_ag               0.022653
inn_prod              0.021361
market                0.020829
mortgage              0.020240
size                  0.019811
age                   0.019044
boss_experience       0.016680
Int_property          0.014563
papers                0.011310
inn_act               0.009813
green                 0.007366
organizational_inn    0.004510
wifi                  0.003133
MBA                   0.001709
dtype: float64

**Интерпретация результатов**  
В обоих моделях `passport` является главной переменной для разделение компаний на инновационно активные и неактивные, однако в случайном лесе важность этого показателя чрезвычайно высокая.\
\
Показатели качества классификаторов (accuracy, precision и так далее) почти не отличаются в моделях, поэтому сделать выбор в пользу какой-либо модели в данной случае не удается.

**Удаление 5 переменных из датасета для новых моделей**  
В этом задании необходимо удалить переменные исходя только из здравого смысла.
* `passport` - можно предположить, что наличие загранпаспорта позволяет сотрудникам, например, ездить на иностранные конференции для обмена идеями, что помогло бы компании быть более инновационной. Однако, анализ этого датасета показал, что корреляция между `passport` и `Answer` негативная. Так, такая корреляция не имеет никакого смысла, поэтому мы ее убираем
* `wifi` - наличие открытой сети является скорее решением ИТ поддержки, и, соответственно, может служить индикатором деятельности только службы ИТ поддержки
* `green` - озеленненность офиса (кол-во растений) хоть и решается сотрудниками компании, но он может служить только индикатором любви сотрудников к растениям
* `mortgage` - наличие ипотеки у сотрудников не влияет на инновационность компании
* `papers` - научные статьи содержат теоретическую основу, а потому редко приводят к каким-либо инновациям. Также нужно иметь ввиду, что существуют разные типы инноваций - например, маркетинговая или организационная инновация - к которой научная статья явно бы не привела. Из-за крайне слабой связи переменная убирается

## Задание 3. Обучите модель градиентного бустинга на новых переменных

In [ ]:
df_2 = df.drop(columns=['passport', 'wifi', 'green', 'mortgage', 'papers'])

X = df_2.drop(columns='Answer')
y = df_2['Answer']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)

In [ ]:
clf = GradientBoostingClassifier(max_depth=3).fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)
y_true = y_test

accuracy = accuracy_score(y_true, y_pred)
print(f'Accuracy: {accuracy:.4f}')

precision = precision_score(y_true, y_pred)
print(f'Precision: {precision:.4f}')

recall = recall_score(y_true, y_pred)
print(f'Recall: {recall:.4f}')

f1 = f1_score(y_true, y_pred)
print(f'F1 Score: {f1:.4f}')

conf_matrix = confusion_matrix(y_true, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_true, y_pred)
print('Classification Report:')
print(class_report)

Accuracy: 0.9341
Precision: 0.9403
Recall: 0.9130
F1 Score: 0.9265
Confusion Matrix:
[[236  12]
 [ 18 189]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       248
           1       0.94      0.91      0.93       207

    accuracy                           0.93       455
   macro avg       0.93      0.93      0.93       455
weighted avg       0.93      0.93      0.93       455



In [ ]:
pd.Series(index = clf.feature_names_in_, data = clf.feature_importances_).sort_values(ascending = False)

climate               0.233246
novelty               0.213542
technologe_acq        0.132247
competition           0.106250
RD                    0.099227
marketing_inn         0.053521
main_ag               0.052664
market                0.034585
novelty_tech          0.020962
age                   0.016367
inn_prod              0.011943
boss_experience       0.008254
inn_act               0.007253
Int_property          0.007046
size                  0.002211
organizational_inn    0.000523
MBA                   0.000159
dtype: float64

## Задание 4. Обучите модель случайного леса на новых переменных и сравните результаты с градиентным бустингом

In [ ]:
randomforest = ensemble.RandomForestClassifier(max_depth=3)
randomforest.fit(X_train, y_train)

RandomForestClassifier(max_depth=3)

In [ ]:
y_pred = randomforest.predict(X_test)
y_true = y_test

accuracy = accuracy_score(y_true, y_pred)
print(f'Accuracy: {accuracy:.4f}')

precision = precision_score(y_true, y_pred)
print(f'Precision: {precision:.4f}')

recall = recall_score(y_true, y_pred)
print(f'Recall: {recall:.4f}')

f1 = f1_score(y_true, y_pred)
print(f'F1 Score: {f1:.4f}')

conf_matrix = confusion_matrix(y_true, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_true, y_pred)
print('Classification Report:')
print(class_report)

Accuracy: 0.8835
Precision: 0.9231
Recall: 0.8116
F1 Score: 0.8638
Confusion Matrix:
[[234  14]
 [ 39 168]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       248
           1       0.92      0.81      0.86       207

    accuracy                           0.88       455
   macro avg       0.89      0.88      0.88       455
weighted avg       0.89      0.88      0.88       455



In [ ]:
pd.Series(index = randomforest.feature_names_in_, data = randomforest.feature_importances_).sort_values(ascending = False)

climate               0.227234
novelty               0.212364
technologe_acq        0.183583
RD                    0.105615
marketing_inn         0.052112
competition           0.039227
inn_prod              0.039006
main_ag               0.037629
novelty_tech          0.030211
market                0.029320
size                  0.014934
inn_act               0.011417
boss_experience       0.006705
Int_property          0.006566
age                   0.003969
organizational_inn    0.000090
MBA                   0.000018
dtype: float64

**Сравнение моделей, обученных на новых переменных**  
На новых переменных модель градиентного бустинга показала себя лучше модели случайного леса, что видно по accuracy (93 против 88), а также по confusion matrix. Модель градиентного бустинга сделала меньше ошибок, особенно второго типа (False Negative).

В качестве главной метрики сравнения моделей принимаем F-1 score, так как этот показатель является средним гармоническим между precision и recall. Данная метрика лучше у модели градиентного бустинга (93 против 86) и мы принимаем ее как оптимальную.